### ISSUE TITLE
"[download] Limit reached for max number of failed attempts`"

### ISSUE THREAD

**Issue by molakirlee** [osmoscraft/osmosfeed-template#4]
Hi, 

I met a problem "[download] Limit reached for max number of failed attempts`" sometimes. I think it is because the RSS source is not stable enough. Is there any way to increase the max num of attempts? Or any other method to deal with this error?

Thank you very much,
Xilock

```
[get-cache] Use remote cache: https://molakirlee.github.io/feed/cache.json
[discover-cache] Pre-build cache restored: https://molakirlee.github.io/feed/cache.json
[enrich] 0.16s |  30 cached |   0 new | https://rsshub.app/geekpark/breakingnews
[enrich] 3.85s |  36 cached |   1 new | https://sspai.com/feed
[download] 2 attempts left, error download https://rsshub.app/wallstreetcn/news/global ECONNABORTED
[download] 2 attempts left, error download https://rsshub.app/bbc/world-asia ECONNABORTED
[download] 2 attempts left, error download https://rsshub.app/wallstreetcn/live ECONNABORTED
[download] 1 attempts left, error download https://rsshub.app/wallstreetcn/news/global ECONNABORTED
[download] 1 attempts left, error download https://rsshub.app/bbc/world-asia ECONNABORTED
[download] 1 attempts left, error download https://rsshub.app/wallstreetcn/live ECONNABORTED
[download] 0 attempts left, error download https://rsshub.app/wallstreetcn/news/global ECONNABORTED
/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31614
      throw new Error(`[download] Limit reached for max number of failed attempts`);
            ^

Error: [download] Limit reached for max number of failed attempts
    at downloadHelper (/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31614:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:526:9)
    at processTimers (node:internal/timers:500:7)
    at async enrichInternal (/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31664:21)
    at async Promise.all (index 2)
    at async run (/home/runner/work/feed/feed/node_modules/@osmoscraft/osmosfeed/bin/main.js:31875:27)
Error: Process completed with exit code 1.
```

**Comment by philippnagel** [comment]
I am getting the same error, although not after enriching an RSS link: 

`  npm run build
  shell: /usr/bin/bash -e {0}
[discover-cache] No cache found: https://philippnagel.com/feeds/cache.json

/home/runner/work/feeds/feeds/node_modules/@osmoscraft/osmosfeed/bin/main.js:31614
> osmosfeed-template@1.0.0 build
      throw new Error(`[download] Limit reached for max number of failed attempts`);
> osmosfeed
`
